### PR TITLE
adds short id to submissions

### PR DESCRIPTION
**Pull request by hernanat**
https://trello.com/c/fFuwQ1Lb

### CODE REVIEW

**Comment by hernanat** [comment]
[add short id support for nicer links](https://trello.com/c/fFuwQ1Lb/29-add-short-id-support-for-nicer-links)

**Comment by hernanat** [comment]
Screen Shot 2020-05-16 at 12 19 31 PM

**Comment by hernanat** [comment]
instead of putting arbitrary integers in the URL we can do this instead, which is much nicer :)

**Comment by ashpil** [comment]
This seems like something we can just merge, right?

**Comment by hernanat** [comment]
I think so -- just didn't know if you wanted to take a look / make any comments before I did. If you're good to go then I'll send it in!

**Comment by hernanat** [comment]
thanks @ashpil !

**Pull request merged**
